#ifndef _INCLUDE_ORPHEU_VERSION_INFORMATION_H_
#define _INCLUDE_ORPHEU_VERSION_INFORMATION_H_

/**
 * @file Contains Orpheu version information.
 * @brief This file will redirect to an autogenerated version if being compiled via
 * the build scripts.
 */

#if defined ORPHEU_GENERATED_BUILD
	#if defined RC_COMPILE
		#undef ORPHEU_USE_VERSIONLIB
	#endif
	#if defined ORPHEU_USE_VERSIONLIB
		#include <versionlib.h>
	#else 
		#include <orpheu_version_auto.h>
	#endif
#else
	#define ORPHEU_BUILD_TAG        "manual"
	#define ORPHEU_BUILD_LOCAL_REV  "0"
	#define ORPHEU_BUILD_CSET       "0"
	#define ORPHEU_BUILD_MAJOR      "2"
	#define ORPHEU_BUILD_MINOR      "6"
	#define ORPHEU_BUILD_RELEASE    "3"

	#define ORPHEU_BUILD_UNIQUEID ORPHEU_BUILD_LOCAL_REV ":" ORPHEU_BUILD_CSET

	#define ORPHEU_VERSION_STRING   ORPHEU_BUILD_MAJOR "." ORPHEU_BUILD_MINOR "." ORPHEU_BUILD_RELEASE "-" ORPHEU_BUILD_TAG
	#define ORPHEU_VERSION_FILE     2,6,3,0
#endif

#define ORPHEU_BUILD_TIMESTAMP  __DATE__ " " __TIME__

#if !defined(ORPHEU_GENERATED_BUILD) || !defined(ORPHEU_USE_VERSIONLIB)
	#define ORPHEU_VERSION      ORPHEU_VERSION_STRING
	#define ORPHEU_BUILD_ID     ORPHEU_BUILD_UNIQUEID
	#define ORPHEU_BUILD_TIME   ORPHEU_BUILD_TIMESTAMP
#endif

#endif /* _INCLUDE_ORPHEU_VERSION_INFORMATION_H_ */

